# frontend/Dockerfile.dev React フロントエンド
FROM node:24.12.0

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 5173

# Viteが自分自身からしかアクセスできないため、全てのネットワークアクセスを受け入れられるように --host 0.0.0.0 を指定
CMD [ "npm", "run", "dev", "--host", "0.0.0.0" ]
