# frontend/Dockerfile.dev React フロントエンド
FROM node:24.12.0

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

EXPOSE 5173

# Viteが自分自身からしかアクセスできないため、全てのネットワークアクセスを受け入れられるように --host 0.0.0.0 を指定
# npm scripts の指定で、--以降は実行するスクリプトにそのまま渡される
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
