# Dockerfile.dev Rails バックエンド
FROM ruby:4.0.0

# 作業ディレクトリの設定
WORKDIR /rails

# パッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y \
      build-essential \
      git \
      sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Gemfile をコピーして、bundle install を実行
COPY Gemfile* ./
RUN bundle install

# アプリケーションコードをコピー
COPY . .

# 3000ポートを公開
EXPOSE 3000

# 開発サーバー起動
CMD ["rails", "server", "-b", "0.0.0.0"]
